version: "2"

services:
    # The webserver facing outside and doing the redirects
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./vhost.d:/etc/nginx/vhost.d
            - ./html:/usr/share/nginx/html
            - /docker/ssl:/etc/nginx/certs:ro
        networks:
            - outside
        labels:
            -com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"


    # The magic part: creating configs and redirects automatically from docker container configs
    docker_gen:
        image: jwilder/docker-gen
        container_name: nginx-gen
        depends_on: 
            - nginx
        volumes_from: 
            - nginx
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./template/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
        links:
            - nginx
        networks:
            - outside

        command: "-notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

    # More magic: automatical creation and renewal of certificates for all services
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx_letsencrypt
        environment:
            - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
        volumes_from: 
            - nginx
        volumes:
            - /docker/ssl:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - inside

networks:
    inside:
    outside:
        external:
            name: proxy-tier
